napiVersion: v1
kind: Service
metadata:
  labels:
    app: hadoop-exporter
  name: hadoop-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9123
  selector:
    app: hadoop-exporter
