apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: hadoop-exporter
  name: hadoop-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  jobLabel: ""
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: hadoop-exporter
