apiVersion: v1
kind: Service
metadata:
  labels:
    app: elastic-exporter
  name: elastic-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9114
  selector:
    app: elastic-exporter
  type: NodePort
