apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: mysqld-exporter
  name: mysqld-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: mysqld-exporter
