apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysqld-exporter
  name: mysqld-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    port: 9104
  selector:
    app: mysqld-exporter
