apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: presto-exporter
  name: presto-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: presto-exporter
  template:
    metadata:
      labels:
        app: presto-exporter
    spec:
      containers:
      - args:
        - --web.url=http://presto:8080/v1/cluster
        image: yahoojapan/presto-exporter:master
        imagePullPolicy: IfNotPresent
        name: presto-exporter
        ports:
        - containerPort: 9483
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 9
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
