apiVersion: v1
kind: Service
metadata:
  labels:
    app: presto-exporter
  name: presto-exporter
  namespace: monitoring
spec:
  ports:
  - name: metrics
    nodePort: 32176
    port: 9483
    protocol: TCP
    targetPort: metrics
  selector:
    app: presto-exporter
  sessionAffinity: None
